# Sử dụng image Nginx siêu nhẹ
FROM nginx:alpine

# Copy file index.html từ máy bạn vào thư mục mặc định của Nginx trong container
COPY index.html /usr/share/nginx/html/index.html

# Mở cổng 80 (cổng mặc định của Nginx)
EXPOSE 80